# Site settings
title: Yondmn's Blog
SEOTitle: 杨明的博客 | Yondmn
header-img: img/home-bg.jpg
email: yondmn@gmamil.com
description: "Weekend. We can."
keyword: "前端开发, yondmn, 杨明的博客, JavaScript, @yondmn"
url: "https://yondmn.cn"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username:     yondmn
#zhihu_username:    yondmn
github_username:    yondmn
twitter_username:   yondmn
#facebook_username: yondmn
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: yondmn

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics
ba_track_id: 81f5525033c6774262ce60bfdf938b0e
# Google Analytics
ga_track_id: 'UA-71624738-1'            # Format: UA-xxxxxx-xx
ga_domain: yondmn.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "多打怪，多升级，让自己变强大。"
sidebar-avatar: /img/avatar-ym.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
        title: "帅小陶",
        href: "https://ht920.com"
    },{
        title: "Yondmn",
        href: "https://ym250.cn"
    },{
        title: "百威",
        href: "//baiwn.com"
    }
]